# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20160505_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='university_1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university_2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university_3',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
