# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to='company_logo'),
        ),
    ]
