# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20160504_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
